// Generated by CoffeeScript 1.7.0
(function() {
  var Log, fs, task,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Log = require('../log');

  fs = require('fs');

  task = function() {
    this.jobsToClean || (this.jobsToClean = ['build', 'deploy']);
    return function(params) {
      var job, jobname, tasksToClean, _i, _len, _ref, _results;
      tasksToClean = [];
      _ref = this.job.app.jobs;
      for (jobname in _ref) {
        job = _ref[jobname];
        if (__indexOf.call(this.jobsToClean, jobname) >= 0) {
          tasksToClean = tasksToClean.concat(job.tasks);
        }
      }
      _results = [];
      for (_i = 0, _len = tasksToClean.length; _i < _len; _i++) {
        task = tasksToClean[_i];
        if (task.target && fs.existsSync(task.target)) {
          _results.push(Log.info("- removing <yellow>" + task.target + "</yellow>"));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
  };

  module.exports = task;

}).call(this);
