// Generated by CoffeeScript 1.7.0
(function() {
  var Log, fs, task,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Log = require('../log');

  fs = require('fs');

  task = function() {
    this.jobsToClean = ['build', 'deploy'];
    return function(params) {
      var job, tasksToClean, _i, _j, _len, _len1, _ref, _results;
      tasksToClean = [];
      _ref = this.job.app.jobs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        job = _ref[_i];
        if (__indexOf.call(this.jobsToClean, job) >= 0) {
          tasksToClean.concat(job.tasks);
        }
      }
      _results = [];
      for (_j = 0, _len1 = tasksToClean.length; _j < _len1; _j++) {
        task = tasksToClean[_j];
        if (fs.existsSync(task.target)) {
          Log.info("- removing <yellow>" + task.target + "</yellow>");
          _results.push(fs.unlinkSync(task.target));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
  };

  module.exports = task;

}).call(this);
