// Generated by CoffeeScript 1.7.0
(function() {
  var Stitch, task, uglifycss;

  uglifycss = require('uglifycss');

  Stitch = require('../stitch');

  task = function() {
    this.targetExt = "css";
    this.bundle = true;
    this.stitch || (this.stitch = new Stitch(this.src, "css"));
    return function(params) {
      var ex, source;
      if (params.watch) {
        Stitch.remove(params.watch);
      }
      try {
        source = this.stitch.resolve({
          bundle: this.bundle
        });
        if (this.argv().compress) {
          source = uglifycss.processString(source);
        }
      } catch (_error) {
        ex = _error;
        this.handleError(ex);
        return "";
      }
      return this.write(source);
    };
  };

  module.exports = task;

}).call(this);
