// Generated by CoffeeScript 1.7.0
(function() {
  var fs, path, requireCss, task, uglifycss, utils;

  uglifycss = require('uglifycss');

  path = require('path');

  fs = require('fs');

  uglifycss = require('uglifycss');

  utils = require('../utils');

  requireCss = function(filepath) {
    filepath = require.resolve(path.resolve(filepath));
    delete require.cache[filepath];
    return require(filepath);
  };

  task = function() {
    this.targetExt = "css";
    this.bundle = true;
    return function(params) {
      var ex, file, fileOrDir, output, result, _i, _j, _len, _len1, _ref, _ref1;
      try {
        output = [];
        _ref = this.src;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          fileOrDir = _ref[_i];
          if (utils.isDirectory(fileOrDir)) {
            _ref1 = fs.readdirSync(fileOrDir);
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              file = _ref1[_j];
              if (!require.extensions[path.extname(file)]) {
                continue;
              }
              file = path.resolve(fileOrDir, file);
              output.push(requireCss(file));
            }
          } else {
            output.push(requireCss(fileOrDir));
          }
        }
        result = output.join("\n");
        if (this.argv.compress) {
          result = uglifycss.processString(result);
        }
        return result;
      } catch (_error) {
        ex = _error;
        this.handleError(ex);
        return "";
      }
    };
  };

  module.exports = task;

}).call(this);
