// Generated by CoffeeScript 1.7.0
(function() {
  var Stitch, task;

  Stitch = require('../stitch');

  task = function() {
    this.targetExt = "css";
    this.bundle = true;
    return function(next) {
      var ex, result, results, _i, _len;
      try {
        this.stitch || (this.stitch = new Stitch(this.src, "css"));
        results = this.stitch.resolve({
          bundle: this.bundle
        });
        if (Array.isArray(results)) {
          for (_i = 0, _len = results.length; _i < _len; _i++) {
            result = results[_i];
            result.target = "???";
            result.route = "???";
          }
        } else {
          results.target = this.target;
          results.route = this.route;
        }
        return next(null, results);
      } catch (_error) {
        ex = _error;
        return next(ex);
      }
    };
  };

  module.exports = task;

}).call(this);
