// Generated by CoffeeScript 1.7.0
(function() {
  var Dependency, Log, Stitch, compile, compileLibs, compileModules, path, task, uglifyjs, utils;

  Dependency = require('../dependency');

  Stitch = require('../stitch');

  Log = require('../log');

  utils = require('../utils');

  path = require('path');

  uglifyjs = require('uglify-js');

  compile = function(task) {
    var ex, result;
    try {
      result = [task.before, compileLibs(task.libs), compileModules(task), task.after].join("\n");
      if (task.job.argv.compress) {
        result = uglifyjs.minify(result, {
          fromString: true
        }).code;
      }
      return result;
    } catch (_error) {
      ex = _error;
      task.handleError(ex);
      return "";
    }
  };

  compileModules = function(task) {
    var _modules;
    task.stitch || (task.stitch = new Stitch(task.src));
    task.depend || (task.depend = new Dependency(task.modules));
    _modules = task.depend.resolve().concat(task.stitch.resolve());
    if (_modules) {
      return Stitch.template(task.commonjs, _modules);
    } else {
      return "";
    }
  };

  compileLibs = function(files, parentDir) {
    var dir, file, results, slash, stats, _i, _len, _ref;
    if (parentDir == null) {
      parentDir = "";
    }
    results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      slash = parentDir === "" ? "" : path.sep;
      file = parentDir + slash + file;
      if (fs.existsSync(file)) {
        stats = fs.lstatSync(file);
        if (stats.isDirectory()) {
          dir = fs.readdirSync(file);
          results.push(compileLibs(task, dir, file));
        } else if (stats.isFile() && ((_ref = path.extname(file)) === '.js' || _ref === '.coffee')) {
          results.push(fs.readFileSync(file, 'utf8'));
        }
      }
    }
    return results.join("\n");
  };

  task = function() {
    this.targetExt = "js";
    this.bundle = true;
    this.commonjs || (this.commonjs = 'required');
    this.before = utils.arrayToString(this.before || "");
    this.after = utils.arrayToString(this.after || "");
    this.depends = utils.toArray(this.depends);
    return function(params) {
      var dirname, extra, source, write;
      if (params.watch) {
        Stitch.clear(params.watch);
      }
      extra = (this.job.argv.compress && " <b>--using compression</b>") || "";
      Log.info("- Building target: <yellow@target}</yellow>" + extra);
      source = compile(this);
      write = this.job.argv.command !== "server";
      if (source && write) {
        dirname = path.dirname(task.target);
        if (!fs.existsSync(dirname)) {
          fs.mkdirsSync(dirname);
        }
        fs.writeFileSync(task.target, source);
      }
      return source;
    };
  };

  module.exports = task;

}).call(this);
