// Generated by CoffeeScript 1.7.0
(function() {
  var Application, Events, Job, Log, Path, Utils, fs, glob, path, uglifyjs,
    __slice = [].slice;

  fs = require('fs-extra');

  path = require('path');

  uglifyjs = require('uglify-js');

  glob = require('globule');

  Utils = require('./utils');

  Events = require('./events');

  Log = require('./log');

  Job = require('./job');

  Application = (function() {
    function Application(name, config, argv) {
      var baseConfig, defaults, err, job, jobname, route, value, _ref, _ref1;
      this.argv = argv;
      this.name = name;
      if (config.base) {
        try {
          baseConfig = Utils.loadAsset('config/' + config.base);
          defaults = Utils.extend({}, baseConfig);
        } catch (_error) {
          err = _error;
          Log.errorAndExit("Invalid 'base' value provided: " + config.base);
        }
        config = Utils.extend(defaults, config);
      }
      this.route = config.route;
      this.root = config.root;
      this["static"] = [];
      this.jobs = {};
      this.defaults = config.defaults || {};
      if (!this.root) {
        if (Utils.isDirectory(this.name)) {
          this.root = this.name;
          this.route || (this.route = "/" + this.name);
        } else {
          this.root = "/";
          this.route || (this.route = "/");
        }
      }
      _ref = config["static"];
      for (route in _ref) {
        value = _ref[route];
        this["static"].push({
          url: this.applyRoute(route),
          path: this.applyRoot(value)
        });
      }
      _ref1 = config.jobs;
      for (jobname in _ref1) {
        value = _ref1[jobname];
        job = new Job(this, jobname, value);
        if (job.tasks.length > 0) {
          this.jobs[jobname] = job;
        }
      }
    }

    Application.prototype.isMatchingRoute = function(route) {
      var item, result, task, _i, _j, _len, _len1, _ref;
      _ref = this.jobs.build.tasks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        task = _ref[_i];
        if (!(route === task.route)) {
          continue;
        }
        result = this.jobs.build.run(task.id);
        if (Array.isArray(result)) {
          for (_j = 0, _len1 = result.length; _j < _len1; _j++) {
            item = result[_j];
            if (route === item.result) {
              return item;
            }
          }
        } else {
          result;
        }
      }
    };

    Application.prototype.watch = function(jobname) {
      var job;
      job = this.jobs[jobname];
      if (job) {
        return job.watch();
      }
    };

    Application.prototype.exec = function(jobname) {
      var job;
      job = this.jobs[jobname];
      if (job) {
        return job.run();
      } else {
        return Log.errorAndExit("ERROR: " + jobname + " job has not been configured.");
      }
    };

    Application.prototype.clean = function() {
      return this.exec('clean');
    };

    Application.prototype.build = function() {
      return this.exec('build');
    };

    Application.prototype.deploy = function() {
      return this.exec('deploy');
    };

    Application.prototype.test = function() {
      return this.exec('test');
    };

    Application.prototype.applyRoot = function(values) {
      var returnArray;
      returnArray = Array.isArray(values);
      values = Utils.toArray(values);
      values = values.map((function(_this) {
        return function(value) {
          if (Utils.startsWith(value, "." + path.sep)) {
            return value;
          } else {
            return Utils.cleanPath(_this.root, value);
          }
        };
      })(this));
      if (returnArray) {
        return values;
      } else {
        return values[0];
      }
    };

    Application.prototype.applyRoute = function() {
      var values;
      values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.route) {
        values.unshift(this.route);
      }
      return Utils.cleanRoute.apply(Utils, values);
    };

    Application.prototype.createPaths = function(paths) {
      var _i, _len, _ref, _results;
      _ref = Utils.toArray(paths);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        path = _ref[_i];
        _results.push(new Path(this, path));
      }
      return _results;
    };

    return Application;

  })();

  Path = (function() {
    function Path(app, options) {
      if (typeof options === "string") {
        if (options.match(/[*]/)) {
          options = {
            srcBase: "",
            src: options
          };
        } else {
          options = {
            srcBase: options,
            src: "**"
          };
        }
      }
      if (app.defaults.commonjs != null) {
        if (options.commonjs == null) {
          options.commonjs = app.defaults.commonjs;
        }
      }
      if (app.defaults.npm != null) {
        if (options.npm == null) {
          options.npm = app.defaults.npm;
        }
      }
      this.src = options.src;
      this.srcBase = app.applyRoot(options.srcBase || "");
      if (options.target) {
        this.target = options.target;
      }
      if (options.commonjs) {
        this.commonjs = options.commonjs;
      }
      if (options.npm) {
        this.npm = options.npm;
      }
    }

    Path.prototype.walk = function() {
      return glob.find({
        src: this.src,
        srcBase: this.srcBase,
        prefixBase: true
      });
    };

    Path.prototype.contains = function(file) {
      return glob.isMatch();
    };

    Path.prototype.mapping = function(destBase) {
      return glob.mapping({
        src: ["a.js", "b.js"],
        srcBase: "foo",
        destBase: "bar"
      });
    };

    return Path;

  })();

  module.exports.create = function(name, config, argv) {
    return new Application(name, config, argv);
  };

}).call(this);
