// Generated by CoffeeScript 1.7.0
(function() {
  var Application, Events, Job, Log, fs, path, uglifyjs, utils,
    __slice = [].slice;

  fs = require('fs-extra');

  path = require('path');

  uglifyjs = require('uglify-js');

  utils = require('./utils');

  Events = require('./events');

  Log = require('./log');

  Job = require('./job');

  Application = (function() {
    function Application(name, config, argv) {
      var baseConfig, defaults, err, job, jobname, route, value, _ref, _ref1;
      this.argv = argv;
      this.name = name;
      if (config.base) {
        try {
          baseConfig = utils.loadAsset('config/' + config.base);
          defaults = utils.extend({}, baseConfig);
        } catch (_error) {
          err = _error;
          Log.error("Invalid 'base' value provided: " + config.base);
          process.exit(1);
        }
        config = utils.extend(defaults, config);
      }
      this.route = config.route;
      this.root = config.root;
      this["static"] = [];
      this.jobs = {};
      if (!this.root) {
        if (utils.isDirectory(this.name)) {
          this.root = this.name;
          this.route || (this.route = "/" + this.name);
        } else {
          this.root = "/";
          this.route || (this.route = "/");
        }
      }
      _ref = config["static"];
      for (route in _ref) {
        value = _ref[route];
        this["static"].push({
          url: this.applyRoute(route),
          path: this.applyRoot(value)[0]
        });
      }
      _ref1 = config.jobs;
      for (jobname in _ref1) {
        value = _ref1[jobname];
        job = new Job(this, jobname, value);
        if (job.tasks.length > 0) {
          this.jobs[jobname] = job;
        }
      }
    }

    Application.prototype.isMatchingRoute = function(route) {
      var params, task, _i, _len, _ref;
      if (this.jobs.version) {
        params = {
          route: route
        };
        this.jobs.version.run(params);
        route = params.route;
      }
      _ref = this.jobs.build.tasks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        task = _ref[_i];
        if (route === task.route) {
          return task.run();
        }
      }
    };

    Application.prototype.exec = function(jobname, params) {
      var job;
      job = this.jobs[jobname];
      if (job) {
        return job.run(params);
      } else {
        return Log.errorAndExit("ERROR: " + jobname + " job has not been configured.");
      }
    };

    Application.prototype.clean = function() {
      return this.exec('clean');
    };

    Application.prototype.build = function() {
      return this.exec('build');
    };

    Application.prototype.deploy = function() {
      return this.exec('deploy');
    };

    Application.prototype.applyRoot = function(value, returnArray) {
      var values;
      if (returnArray == null) {
        returnArray = true;
      }
      values = utils.toArray(value);
      values = values.map((function(_this) {
        return function(value) {
          if (utils.startsWith(value, "." + path.sep)) {
            return value;
          } else {
            return utils.cleanPath(_this.root, value);
          }
        };
      })(this));
      if (returnArray) {
        return values;
      } else {
        return values[0];
      }
    };

    Application.prototype.applyRoute = function() {
      var values;
      values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.route) {
        values.unshift(this.route);
      }
      return utils.cleanRoute.apply(utils, values);
    };

    return Application;

  })();

  module.exports.create = function(name, config, argv) {
    return new Application(name, config, argv);
  };

}).call(this);
