// Generated by CoffeeScript 2.7.0
(function() {
  // ------ Setup shareable events emitter
  var events;

  events = new require('events');

  module.exports = new events.EventEmitter();

}).call(this);
