// Generated by CoffeeScript 1.8.0
(function() {
  var log, sty;

  sty = require('sty');

  log = function(message, parse) {
    if (parse == null) {
      parse = true;
    }
    return console.log(parse && sty.parse(message) || message);
  };

  log.info = function(message, parse) {
    if (parse == null) {
      parse = true;
    }
    if (this.VERBOSE) {
      return console.log(parse && sty.parse(message) || message);
    }
  };

  log.error = function(message, parse) {
    if (parse == null) {
      parse = true;
    }
    return console.log("" + (sty.red('ERROR:')) + " " + (parse && sty.parse(message) || message));
  };

  log.errorAndExit = function(error, parse) {
    if (parse == null) {
      parse = true;
    }
    log.error(error, parse);
    return process.exit(1);
  };

  log.parse = function(message) {
    return sty.parse(message);
  };

  module.exports = log;

}).call(this);
