// Generated by CoffeeScript 1.6.2
(function() {
  var connect, createRoutingProxy, fs, http, mime, patchServerResponseForRedirects, server, utils;

  connect = require('connect');

  mime = require('connect')["static"].mime;

  http = require('http');

  fs = require('fs');

  utils = require('./utils');

  server = {};

  server.start = function(hemapps, options) {
    var app;

    app = connect();
    app.use(server.middleware(app, hemapps, options));
    return http.createServer(app).listen(options.port, options.host);
  };

  server.middleware = function(app, hemapps, options) {
    var hemapp, pkg, route, url, value, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;

    for (_i = 0, _len = hemapps.length; _i < _len; _i++) {
      hemapp = hemapps[_i];
      if (hemapp.url && utils.VERBOSE) {
        _ref = hemapp.packages;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          pkg = _ref[_j];
          utils.log("Map application target '" + pkg.target + "' to " + pkg.route);
        }
      }
      if (hemapp["static"]) {
        options.routes = utils.extend(options.routes, hemapp["static"]);
      }
    }
    _ref1 = options.routes;
    for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
      route = _ref1[_k];
      url = Object.keys(route)[0];
      value = route[url];
      if (typeof value === 'string') {
        if (fs.existsSync(value)) {
          utils.verbose("Map directory '" + value + "' to " + url);
          app.use(url, connect["static"](value));
        } else {
          utils.errorAndExit("The folder " + value + " does not exist.");
        }
      } else if (value.host) {
        utils.verbose("Proxy requests from " + url + " to " + value.host);
        app.use(url, createRoutingProxy(value));
      } else {
        throw new Error("Invalid route configuration for " + url);
      }
    }
    return function(req, res, next) {
      var str, _l, _len3, _ref2;

      url = ((_ref2 = require("url").parse(req.url)) != null ? _ref2.pathname.toLowerCase() : void 0) || "";
      if (url.match(/\.js|\.css/)) {
        for (_l = 0, _len3 = hemapps.length; _l < _len3; _l++) {
          hemapp = hemapps[_l];
          if (pkg = hemapp.isMatchingRoute(url)) {
            str = pkg.compile(!debug);
            res.charset = 'utf-8';
            res.setHeader('Content-Type', mime.lookup(pkg.target));
            res.setHeader('Content-Length', Buffer.byteLength(str));
            res.end((req.method === 'HEAD' && null) || str);
            return;
          }
        }
      }
      return next();
    };
  };

  createRoutingProxy = function(options) {
    var proxy;

    if (options == null) {
      options = {};
    }
    proxy = new require('http-proxy').RoutingProxy();
    options.hostPath || (options.hostPath = "");
    options.port || (options.port = 80);
    options.patchRedirect || (options.patchRedirect = true);
    if (options.patchRedirect) {
      proxy.once("start", function(req, res) {
        var returnHost;

        returnHost = req.headers.host;
        return patchServerResponseForRedirects(options.host, returnHost);
      });
    }
    return function(req, res, next) {
      req.url = "" + options.hostPath + req.url;
      return proxy.proxyRequest(req, res, options);
    };
  };

  patchServerResponseForRedirects = function(fromHost, returnHost) {
    var writeHead;

    writeHead = http.ServerResponse.prototype.writeHead;
    return http.ServerResponse.prototype.writeHead = function(status) {
      var headers, newLocation, oldLocation;

      if (status === 301 || status === 302) {
        headers = this._headers;
        oldLocation = new RegExp(":\/\/" + fromHost + ":?[0-9]*");
        newLocation = "://" + returnHost;
        headers.location = headers.location.replace(oldLocation, newLocation);
      }
      return writeHead.apply(this, arguments);
    };
  };

  module.exports = server;

}).call(this);
