// Generated by CoffeeScript 1.6.2
(function() {
  var createKarmaFileList, fs, start, startKarma;

  fs = require('fs');

  start = function(packages, options) {
    if (options == null) {
      options = {};
    }
    return startKarma(packages, singleRun);
  };

  startKarma = function(packages, options) {
    var testConfig;

    if (options == null) {
      options = {};
    }
    testConfig = fs.existsSync(options.config) && fs.realpathSync(options.config);
    testConfig || (testConfig = {
      configFile: require.resolve("../assets/testacular.conf.js"),
      singleRun: options.singleRun || true,
      basePath: process.cwd(),
      logLevel: 'error',
      browsers: options.browser && options.browser.split(/[ ,]+/) || ['PhantomJS'],
      files: createKarmaFileList(packages)
    });
    return require('karma').server.start(testConfig);
  };

  createKarmaFileList = function(packages) {
    var fileList, pkg, _i, _len;

    fileList = [require.resolve("../node_modules/karma/adapter/lib/jasmine.js"), require.resolve("../node_modules/karma/adapter/jasmine.js")];
    for (_i = 0, _len = packages.length; _i < _len; _i++) {
      pkg = packages[_i];
      fileList.push(pkg.target);
    }
    return fileList;
  };

  module.exports.start = start;

}).call(this);
